---
- hosts: all
  become: true
  vars_files: tasks/vars/docker-vars.yml

  tasks:
    - name: Install Docker
      import_tasks: tasks/install_docker.yml

    - name: Post Installation Configuration
      import_tasks: tasks/post-install.yaml

    - name: Install Docker Comopse
      import_tasks: tasks/install_docker_compose.yml
